// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBME4T6l-Pr93AdCOaELTnIF7HmLZIq9z0',
    appId: '1:503930873519:android:c2cd93fbb922931e45d65a',
    messagingSenderId: '503930873519',
    projectId: 'thread-b4d7b',
    databaseURL: 'https://thread-b4d7b-default-rtdb.firebaseio.com',
    storageBucket: 'thread-b4d7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv2uybUybmQU_QF-PMGCstICMj-FiUtQE',
    appId: '1:503930873519:ios:e486ebdcf4e1dadb45d65a',
    messagingSenderId: '503930873519',
    projectId: 'thread-b4d7b',
    databaseURL: 'https://thread-b4d7b-default-rtdb.firebaseio.com',
    storageBucket: 'thread-b4d7b.firebasestorage.app',
    androidClientId: '503930873519-pbndbp934a7pji5jns0i4sik65rbl6ps.apps.googleusercontent.com',
    iosBundleId: 'com.thread.app.threadApp',
  );

  /// Web configuration — lấy từ Firebase Console → Project Settings → Your apps → Web app
  /// Nếu chưa có Web app, vào Firebase Console tạo mới rồi copy các giá trị vào đây.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBME4T6l-Pr93AdCOaELTnIF7HmLZIq9z0',
    authDomain: 'thread-b4d7b.firebaseapp.com',
    databaseURL: 'https://thread-b4d7b-default-rtdb.firebaseio.com',
    projectId: 'thread-b4d7b',
    storageBucket: 'thread-b4d7b.firebasestorage.app',
    messagingSenderId: '503930873519',
    // TODO: Thay giá trị này bằng Web appId thực từ Firebase Console
    // Firebase Console → Project Settings → Your Apps → Web app → App ID
    appId: '1:503930873519:web:0000000000000000',
  );
}